name: Run R Script  
  
on:  
  push:  
    branches:  
      - main  
  schedule:  
    - cron: "30 17 * * *"  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout Repository  
      uses: actions/checkout@v2  
  
    - name: Set up R  
      uses: r-lib/actions/setup-r@v1  
      with:  
        r-version: '4.x' # Specify the R version you want to use  
  
    - name: Install Dependencies  
      run: |  
        Rscript -e 'install.packages(c("yahoofinancer"))' # Add any required R packages here  
  
    - name: Run Script  
      run: Rscript script.R # Replace script.R with the name of your R script  
