name: Run R Script  
  
on:  
  push:  
    branches:  
      - main  
  schedule:  
    # - cron: "30 17 * * *"  # 17:30
    - cron: "*/15 * * * *" # every 5 MINS
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout Repository  
      uses: actions/checkout@v2  

    - name: Set PKG_CONFIG_PATH  
      run: |  
        export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" 

    - name: Install System Dependencies  
      run: |  
        # sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev  
        sudo apt-get install libcurl4-openssl-dev    
  
    - name: Set up R  
      uses: r-lib/actions/setup-r@v2  
      with:  
        r-version: '4.x' # Specify the R version you want to use  
  
    # - name: Install Dependencies  
    #   run: |  
    #     Rscript -e 'install.packages(c("curl", "httr", "jsonlite", "lubridate", "magrittr", "purrr", "R6", "stringr", "yahoofinancer"))' # Add any required R packages here  
  
    - name: Run Script  
      run: Rscript script.R # Replace script.R with the name of your R script  
      
    - name: Pull Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/*.txt
        git commit -m "Pull from GitHub Actions"
        git pull https://$GITHUB_ACTOR:${{ secrets.YF }}@github.com/$GITHUB_REPOSITORY.git HEAD:main 
        
    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/*.txt
        git commit -m "Update financial data from GitHub Actions"
        git push https://$GITHUB_ACTOR:${{ secrets.YF }}@github.com/$GITHUB_REPOSITORY.git HEAD:main 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}