on:
  schedule:
    - cron:  "0 18 * * 1-5"
  workflow_dispatch:

jobs:  
  build:  
    runs-on: ubuntu-latest  
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  
    steps:  
    - name: Checkout Repository  
      uses: actions/checkout@v2  

    - name: Set PKG_CONFIG_PATH  
      run: |  
        export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" 

    - name: Install System Dependencies  
      run: |  
        Rscript -e "install.packages('tidyverse')"    
  
    - name: Set up R  
      uses: r-lib/actions/setup-r@v2  
      with:  
        r-version: '4.x' # Specify the R version you want to use  
  
    - name: Run Script  
      run: Rscript get_insigths.R # Replace script.R with the name of your R script  
      
    # - name: Run Script delete  
    #  run: Rscript script_del.R # Replace script.R with the name of your R script 

    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "get signals" || echo "No changes to commit"
        git push origin || echo "No changes to commit"-
