on:
  schedule:
    - cron:  "0 18 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2

    - name: Run Script
      run: Rscript get_insigths.R # Replace script.R with the name of your R script

    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "get signals" || echo "No changes to commit"
        git push origin || echo "No changes to commit"-

# on:
#   schedule:
#     - cron: "36 18 * * 1-5"
#   workflow_dispatch:
# 
# jobs:  
#   build:  
#     runs-on: ubuntu-latest  
#     env:
#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
# 
#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2
# 
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'
# 
#     - name: Install Dependencies
#       run: |
#         pip install -r requirements.txt
# 
#     - name: Run py script
#       run: |
#         python get_insigths.py
# 
#     - name: Commit results
#       run: |
#         git config --local user.email "actions@github.com"
#         git config --local user.name "GitHub Actions"
#         git add .
#         git commit -m "get get_insigths" || echo "No changes to commit"
#         git push origin || echo "No changes to commit"
